#!/usr/bin/env bash

# update local or global installed npm packages

function usage() {
    echo "Usage: $(basename $0) [-u -g -h]" 1>&2
    echo "Options are:" 1>&2
    echo "  -u update packages" 1>&2
    echo "  -g go global" 1>&2
    echo "  -h show this help" 1>&2
    echo "If not options are given, local packages will be listed." 1>&2
    exit 1
}

global=""
update=""

while getopts "ugh" o; do
    case "${o}" in
        u)
            update="1"
            ;;
        g)
            global="--global"
            ;;
	h)
	    usage
	    ;;
	*)
	    ;;
    esac
done



packages=$(npm $global list -depth 0 --parseable 2>/dev/null | tail -n +2 | xargs basename | grep -v npm)

if [[ -z $update ]]; then
    case "$global" in
	--global) location="GLOBAL" ;;
	*) location="LOCAL" ;;
    esac
    msg="Listing ${location} packages. Run $(basename $0) -h for other options."
    echo $msg
    yes "-" | tr -d '\n' | head -c ${#msg}
    echo
    echo $packages | tr " " "\n"
else
    npm install $global $packages
    if [[ -n $global ]]; then
	npm install --global --force npm
    fi
fi
